# Generated by Django 2.0.5 on 2018-05-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_href', models.URLField()),
                ('article_title', models.CharField(max_length=100)),
                ('article_writer', models.CharField(max_length=64)),
                ('article_comment', models.TextField()),
                ('article_upvote', models.IntegerField()),
                ('article_downvote', models.IntegerField()),
            ],
        ),
    ]
