# Generated by Django 2.0.5 on 2018-05-26 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('best_comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_crawldate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
